name: Build Doxygen

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-doxygen:
    name: Build Doxygen
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Doxygen
        run: sudo apt-get install -y doxygen graphviz
        shell: bash
      - name: Generate Doxygen Documentation
        run: doxygen Doxygen/Doxyfile
        shell: bash
      - name: Create .nojekyll (ensures pages with underscores work on gh pages)
        run: touch Doxygen/.nojekyll
        shell: bash
      # - name: Upload Doxygen Documentation to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: Doxygen/Generated/html