name: Build Doxygen

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-doxygen:
    name: Build Doxygen
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Dotnet Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: dotnet tool update -g docfx
      - run: docfx docfx.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: _site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
      # - name: Install Doxygen
      #   run: |
      #     sudo apt-get install -y graphviz
      #     mkdir doxygen-install
      #     cd doxygen-install
      #     wget https://www.doxygen.nl/files/doxygen-1.10.0.linux.bin.tar.gz
      #     tar -xvf doxygen-1.10.0.linux.bin.tar.gz
      #     sudo mv doxygen-1.10.0/bin/doxygen /usr/bin/doxygen
      #     cd ..
      #     sudo rm -rf doxygen-install
      #   shell: bash
      # - name: Generate Doxygen Documentation
      #   run: /usr/bin/doxygen Doxygen/Doxyfile
      #   shell: bash
      # - name: Create .nojekyll (ensures pages with underscores work on gh pages)
      #   run: touch Doxygen/.nojekyll
      #   shell: bash
      # - name: Upload Doxygen Documentation to Github Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: Doxygen/Generated/html